TennisApp/Models/Comentario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TennisApp.Models
{
    public class Comentario
    {
        [Key]
        public int IdComentario { get; set; }

        [Required(ErrorMessage = "É necessário preencher o {0}.")]
        [StringLength(200, MinimumLength = 1, ErrorMessage = "O {0} deve ter entre {2} e {1} caracteres.")]
        [DataType(DataType.MultilineText)]
        public string Texto { get; set; }

        [DataType(DataType.Date)]
        public DateTime DataComentario { get; set; }
        
        // tornar comentario visivel ou nao
        public bool Visivel { get; set; }
        
        // um Comentario pertence a UMA Notícia
        [ForeignKey("Noticia")]
        [DisplayName("Notícia")]
        public int NoticiaFK { get; set; }
        public virtual Noticia Noticia        { get; set; }

        // pessoa que coloca o Comentario
        [ForeignKey("Criador")]
        [DisplayName("Autor")]
        public int CriadorFK { get; set; }
        public virtual Utilizador Criador { get; set; }

    }
}

TennisApp/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TennisApp.Models;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;
using System.Text.RegularExpressions;

namespace TennisApp.Controllers
{
    [Authorize]
    public class ComentariosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        /// adiciona um comentário
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(string comentario, int idNoticia)
        {

            if (!string.IsNullOrEmpty( comentario ))
            {
                StringBuilder sbComentarios = new StringBuilder();
                sbComentarios.Append(HttpUtility.HtmlEncode(comentario));

                sbComentarios.Replace("&lt;b&gt;", "<b>");
                sbComentarios.Replace("&lt;/b&gt;", "</b>");
                sbComentarios.Replace("&lt;u&gt;", "<u>");
                sbComentarios.Replace("&lt;/u&gt;", "</u>");
                sbComentarios.Replace("\r\n", "<br />");

                Comentario novoComentario = new Comentario();

                // adicionar dados ao obj que vai levar os dados para a BD
                novoComentario.NoticiaFK = idNoticia;
                novoComentario.CriadorFK = db.Utilizadores.Where(u => u.UserName.Equals(User.Identity.Name)).FirstOrDefault().IdUtilizador;
                novoComentario.DataComentario = DateTime.Now;
                novoComentario.Texto = comentario;
                novoComentario.Visivel = true;

                if (ModelState.IsValid)
                {
                    db.Comentarios.Add(novoComentario);
                    db.SaveChanges();
                    TempData["Create"] = "Comentário adicionado";
                }
                else
                {
                    TempData["Error"] = "Comentário inválido";
                }
            }
            return RedirectToAction("Details", "Noticias", new { Id = idNoticia });
        }
        /// censura um comentário
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Censura(int idComentario, int idNoticia)
        {
            var comentario = db.Comentarios.Find(idComentario);
            comentario.Visivel = false;
            if (ModelState.IsValid)
            {
                db.Entry(comentario).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Edit"] = "";
                return RedirectToAction("Details", "Noticias", new { Id = idNoticia });
            }

            return RedirectToAction("Details", "Noticias", new { Id = idNoticia });
        }

        /// censura um comentário
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult MostraComentario(int idComentario, int idNoticia)
        {
            var comentario = db.Comentarios.Find(idComentario);
            comentario.Visivel = true;
            if (ModelState.IsValid)
            {
                db.Entry(comentario).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Edit"] = "";
                return RedirectToAction("Details", "Noticias", new { Id = idNoticia });
            }

            return RedirectToAction("Details", "Noticias", new { Id = idNoticia });
        }

        // GET: Comentarios
        [AllowAnonymous]
        [OutputCache(Duration = 10)]
        [Authorize(Roles = "Administrador,Moderador")]
        public ActionResult Index(string searchBy, string search, int? page, string sortBy)
        {
            ViewBag.SortAutorParameter = string.IsNullOrEmpty(sortBy) ? "Autor desc" : "";
            ViewBag.SortNoticiaParameter = sortBy == "Noticia" ? "Noticia desc" : "Noticia";

            var comentarios = db.Comentarios.AsQueryable();

            if (searchBy == "Autor")
            {
                comentarios = comentarios.Where(x => x.Criador.Nome.Contains(search) || search == null);
            }
            else if (searchBy == "Noticia")
            {
                comentarios = comentarios.Where(x => x.Noticia.Titulo.Contains(search) || search == null);
            }
            else
            {
                comentarios = comentarios.Where(x => x.Texto.Contains(search) || search == null);
            }
            switch (sortBy)
            {
                case "Autor desc":
                    comentarios = comentarios.OrderByDescending(x => x.Criador.Nome);
                    break;
                case "Noticia desc":
                    comentarios = comentarios.OrderByDescending(x => x.Noticia.Titulo);
                    break;
                case "Noticia":
                    comentarios = comentarios.OrderBy(x => x.Noticia.Titulo);
                    break;
                default:
                    comentarios = comentarios.OrderBy(x => x.Criador.Nome);
                    break;
            }
            return View(comentarios.ToPagedList(page ?? 1, 6));
        }

        // GET: Comentarios/Details/5
        [Authorize(Roles = "Administrador,Moderador")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Comentário inválido";
                return RedirectToAction("Index");
            }
            Comentario comentario = db.Comentarios.Find(id);
            if (comentario == null)
            {
                TempData["Error"] = "Comentário inválido";
                return RedirectToAction("Index");
            }
            return View(comentario);
        }

        // GET: Comentarios/Create
        [ValidateInput(false)]
        [Authorize(Roles = "Administrador,Moderador")]
        public ActionResult Create()
        {
            ViewBag.CriadorFK = new SelectList(db.Utilizadores, "IdUtilizador", "Nome");
            ViewBag.NoticiaFK = new SelectList(db.Noticias, "IdNoticia", "Titulo");
            return View();
        }

        // POST: Comentarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize(Roles = "Administrador,Moderador")]
        public ActionResult Create([Bind(Include = "IdComentario,Texto,DataComentario,Visivel,NoticiaFK,CriadorFK")] Comentario comentario)
        {
            StringBuilder sbComentarios = new StringBuilder();
            sbComentarios.Append(HttpUtility.HtmlEncode(comentario.Texto));

            sbComentarios.Replace("&lt;b&gt;", "<b>");
            sbComentarios.Replace("&lt;/b&gt;", "</b>");
            sbComentarios.Replace("&lt;u&gt;", "<u>");
            sbComentarios.Replace("&lt;/u&gt;", "</u>");
            sbComentarios.Replace("\r\n", "<br />");

            comentario.Texto = sbComentarios.ToString();

            if (ModelState.IsValid)
            {
                db.Comentarios.Add(comentario);
                db.SaveChanges();
                TempData["Create"] = "" + comentario.Criador.Nome;
                return RedirectToAction("Index");
            }

            ViewBag.CriadorFK = new SelectList(db.Utilizadores, "IdUtilizador", "Nome", comentario.CriadorFK);
            ViewBag.NoticiaFK = new SelectList(db.Noticias, "IdNoticia", "Titulo", comentario.NoticiaFK);
            return View(comentario);
        }

        // GET: Comentarios/Edit/5
        [ValidateInput(false)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Comentário inválido";
                return RedirectToAction("Index");
            }
            Comentario comentario = db.Comentarios.Find(id);
            if (comentario == null)
            {
                TempData["Error"] = "Comentário inválido";
                return RedirectToAction("Index");
            }
            // verificar se a pessoa que edita a notícia é um Moderador
            if (User.IsInRole("Moderador"))
            {
                return View(comentario);
            }

            // verificar se a pessoa que edita a notícia é o seu autor
            if (comentario.Criador.UserName.Equals(User.Identity.Name))
            {
                return View(comentario);
            }

            ViewBag.CriadorFK = new SelectList(db.Utilizadores, "IdUtilizador", "Nome", comentario.CriadorFK);
            ViewBag.NoticiaFK = new SelectList(db.Noticias, "IdNoticia", "Titulo", comentario.NoticiaFK);
            TempData["Error"] = "Não tem permissões para editar este comentário";
            return RedirectToAction("Index");
        }

        // POST: Comentarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "IdComentario,Texto,DataComentario,Visivel,NoticiaFK,CriadorFK")] Comentario comentario)
        {

            StringBuilder sbComentarios = new StringBuilder();
            sbComentarios.Append(HttpUtility.HtmlEncode(comentario.Texto));

            sbComentarios.Replace("&lt;b&gt;", "<b>");
            sbComentarios.Replace("&lt;/b&gt;", "</b>");
            sbComentarios.Replace("&lt;u&gt;", "<u>");
            sbComentarios.Replace("&lt;/u&gt;", "</u>");
            sbComentarios.Replace("\r\n", "<br />");

            comentario.Texto = sbComentarios.ToString();

TennisApp/Views/Comentarios/Create.cshtml
@model TennisApp.Models.Comentario

@{
    ViewBag.Title = "Criar um Comentário";
}
@if (TempData["Create"] != null)
{
    <div id="msg" class="alert alert-success fade-in">
        <strong>Notícia criada!</strong>
        A notícia " @TempData["Create"].ToString() " foi criada com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comentário</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Texto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Texto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Texto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataComentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataComentario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataComentario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Visivel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Visivel)
                    @Html.ValidationMessageFor(model => model.Visivel, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoticiaFK, "NoticiaFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NoticiaFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NoticiaFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CriadorFK, "CriadorFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CriadorFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CriadorFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Comentarios/Delete.cshtml
@model TennisApp.Models.Comentario

@{
    ViewBag.Title = "Remover";
}
@if (TempData["Delete"] != null)
{
    <div id="msg" class="alert alert-success fade-in">
        <strong>Notícia editada!</strong>
        O Comentário " @TempData["Delete"].ToString() " foi eliminado com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Remover</h2>

<h3>Tem a certeza que pretende remover?</h3>
<div>
    <h4>Comentário</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Criador.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Criador.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Noticia.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Noticia.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Texto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Texto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataComentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataComentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visivel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-default" /> |
            @Html.ActionLink("Voltar à lista", "Index")
        </div>
    }
</div>
<script>
	$(document).ready(function () {
		// esconde a mensagem de alerta que apareça
		setTimeout(function () {
			$("#msg").fadeOut(1000);
		}, 6000);
	});

</script>

TennisApp/Views/Comentarios/Details.cshtml
@model TennisApp.Models.Comentario

@{
    ViewBag.Title = "Detalhes";
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Detalhes</h2>

<div>
    <h4>Comentário</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Criador.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Criador.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Noticia.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Noticia.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Texto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Texto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataComentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataComentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visivel)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdComentario }) |
    @Html.ActionLink("Voltar à lista", "Index")
</p>
<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Comentarios/Edit.cshtml
@model TennisApp.Models.Comentario

@{
    ViewBag.Title = "Editar";
}
@if (TempData["Edit"] != null)
{
    <div id="msg" class="alert alert-warning fade-in">
        <strong>Comentário editado!</strong>
        O Comentário " @TempData["Edit"].ToString() " foi editado com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comentário</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdComentario)

        <div class="form-group">
            @Html.LabelFor(model => model.Texto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Texto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Texto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataComentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataComentario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataComentario, "", new { @class = "text-danger" })
            </div>
        </div>

        @*se o utilizador for do tipo Moderador, pode censurar*@
        @if (User.IsInRole("Moderador"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Visivel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Visivel)
                        @Html.ValidationMessageFor(model => model.Visivel, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.NoticiaFK, "NoticiaFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NoticiaFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NoticiaFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CriadorFK, "CriadorFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CriadorFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CriadorFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Comentarios/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<TennisApp.Models.Comentario>

@{
    ViewBag.Title = "Lista de Comentários";
}
@if (TempData["Create"] != null)
{
    <div id="msg" class="alert alert-success fade in">
        <strong>Comentário criado!</strong>
        O Comentário " @TempData["Create"].ToString() " foi criado com sucesso.
    </div>
}
@if (TempData["Edit"] != null)
{
    <div id="msg" class="alert alert-warning fade in">
        <strong>Comentário editado!</strong>
        O Comentário " @TempData["Edit"].ToString() " foi editado com sucesso.
    </div>
}
@if (TempData["Delete"] != null)
{
    <div id="msg" class="alert alert-success fade in">
        <strong>Comentário editado!</strong>
        O Comentário " @TempData["Delete"].ToString() " foi eliminado com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Lista de Comentários</h2>
<div>
    @Html.ActionLink("Criar um novo Comentário", "Create")
    @using (Html.BeginForm("Index", "Comentarios", FormMethod.Get))
    {
        <b>Procurar por: </b>
        @Html.RadioButton("searchBy", "Autor", true) <text>Autor</text>
        @Html.RadioButton("searchBy", "Noticia", true) <text>Notícia</text>
        @Html.RadioButton("searchBy", "Texto", true) <text>Texto</text>
        <br />
            @Html.TextBox("search")  <input type="submit" value="Procurar" />
    }

    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Autor", "Index", new { sortBy = ViewBag.SortAutorParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
            </th>
            <th>
                @Html.ActionLink("Notícia", "Index", new { sortBy = ViewBag.SortNoticiaParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Texto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DataComentario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Visivel)
            </th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4"> Não foi encontrado o que procura.</td>
            </tr>
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Criador.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Noticia.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Texto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataComentario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Visivel)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdComentario }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.IdComentario }) |
                    @Html.ActionLink("Remover", "Delete", new { id = item.IdComentario })
                </td>
            </tr>
        }

    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    searchBy = Request.QueryString["searchBy"],
    search = Request.QueryString["search"],
    sortBy = Request["sortBy"]
}),
new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })
</div>

<script>
	$(document).ready(function () {
		// esconde a mensagem de alerta que apareça
		setTimeout(function () {
			$("#msg").fadeOut(1000);
		}, 6000);
	});

</script>