TennisApp/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TennisApp.Models
{
    public class Categoria
    {
        public Categoria()
        {
            this.Noticias = new HashSet<Noticia>();
        }

        [Key]
        public int IdCategoria { get; set; }

        [Required(ErrorMessage = "É necessário um {0}")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "O {0} deve ter entre {2} e {1} caracteres.")]
        [DisplayName("Nome de Categoria")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "É necessário uma {0}.")]
        [DisplayName("Descrição")]
        [StringLength(150, MinimumLength = 10, ErrorMessage = "A {0} deve ter entre {2} e {1} caracteres.")]
        [DataType(DataType.MultilineText)]
        public string Descricao { get; set; }
      
        public virtual ICollection<Noticia> Noticias { get; set; }
    }
}

TennisApp/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TennisApp.Models;
using PagedList;
using PagedList.Mvc;

namespace TennisApp.Controllers
{
    [Authorize(Roles = "Administrador,Moderador")]
    public class CategoriasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categorias
        //metodo search por categoria e descricao
        [AllowAnonymous]
        //tempo(segundos) que fica em cache
        [OutputCache(Duration = 10)]
        public ActionResult Index(string searchBy, string search, int? page, string sortBy)
        {
            ViewBag.SortCategoriaParameter = string.IsNullOrEmpty(sortBy) ? "Categoria desc" : "";

            var categorias = db.Categorias.AsQueryable();

            if (searchBy == "Categoria")
            {
                categorias = categorias.Where(x => x.Nome.Contains(search) || search == null);
            }
            else
            {
                categorias = categorias.Where(x => x.Descricao.Contains(search) || search == null);
            }
            switch (sortBy)
            {
                case "Categoria desc":
                    categorias = categorias.OrderByDescending(x => x.Nome);
                    break;
                default:
                    categorias = categorias.OrderBy(x => x.Nome);
                    break;
            }
            return View(categorias.ToPagedList(page ?? 1, 5));
        }

        public JsonResult GetSearch(string term)
        {
            List<string> categorias;

            categorias = db.Categorias.Where(x => x.Nome.StartsWith(term)).Select(y => y.Nome).ToList();

            return Json(categorias, JsonRequestBehavior.AllowGet);
        }

        // GET: Categorias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Categoria inválida";
                return RedirectToAction("Index");

            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {

                TempData["Error"] = "Categoria inválida";
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: Categorias/Create
        [ValidateInput(false)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "IdCategoria,Nome,Descricao")] Categoria categoria)
        {
            //Selecciona o último id da tabela de categorias e incrementa 1
            var CategoryID = db.Categorias.OrderByDescending(d => d.IdCategoria).FirstOrDefault().IdCategoria + 1;

            // atribui o novo ID ao objeto que veio da View
            categoria.IdCategoria = CategoryID;

            StringBuilder sbCategorias = new StringBuilder();
            sbCategorias.Append(HttpUtility.HtmlEncode(categoria.Descricao));

            sbCategorias.Replace("&lt;b&gt;", "<b>");
            sbCategorias.Replace("&lt;/b&gt;", "</b>");
            sbCategorias.Replace("&lt;u&gt;", "<u>");
            sbCategorias.Replace("&lt;/u&gt;", "</u>");
            sbCategorias.Replace("\r\n", "<br />");

            categoria.Descricao = sbCategorias.ToString();

            string strTitulo = HttpUtility.HtmlEncode(categoria.Nome);
            categoria.Nome = strTitulo;

            if (ModelState.IsValid)
            {
                db.Categorias.Add(categoria);
                db.SaveChanges();
                TempData["Create"] = "" + categoria.Nome;
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        // GET: Categorias/Edit/5
        [ValidateInput(false)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Categoria inválida";
                return RedirectToAction("Index");
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                TempData["Error"] = "Categoria inválida";
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "IdCategoria,Nome,Descricao")] Categoria categoria)
        {
            StringBuilder sbCategorias = new StringBuilder();
            sbCategorias.Append(HttpUtility.HtmlEncode(categoria.Descricao));

            sbCategorias.Replace("&lt;b&gt;", "<b>");
            sbCategorias.Replace("&lt;/b&gt;", "</b>");
            sbCategorias.Replace("&lt;u&gt;", "<u>");
            sbCategorias.Replace("&lt;/u&gt;", "</u>");
            sbCategorias.Replace("\r\n", "<br />");

            categoria.Descricao = sbCategorias.ToString();

            string strTitulo = HttpUtility.HtmlEncode(categoria.Nome);
            categoria.Nome = strTitulo;

            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Edit"] = "" + categoria.Nome;
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Categoria inválida";
                return RedirectToAction("Index");
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                TempData["Error"] = "Categoria inválida";
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult DeleteConfirmed(int id)
        {
            Categoria categoria = db.Categorias.Find(id);
            db.Categorias.Remove(categoria);
            db.SaveChanges();
            TempData["Delete"] = categoria.Nome;
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TennisApp/Views/Categorias/Create.cshtml
@model TennisApp.Models.Categoria

@{
    ViewBag.Title = "Criar";
}
@if (TempData["Create"] != null)
{
    <div id="msg" class="alert alert-success fade-in">
        <strong>Categoria criada!</strong>
        A Categoria " @TempData["Create"].ToString() " foi criada com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Categorias/Delete.cshtml
@model TennisApp.Models.Categoria

@{
    ViewBag.Title = "Remover";
}
@if (TempData["Delete"] != null)
{
    <div id="msg" class="alert alert-success fade-in">
        <strong>Categoria editada!</strong>
        A Categoria " @TempData["Delete"].ToString() " foi eliminada com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Remover</h2>

<h3>Tem a certeza que pretende remover?</h3>
<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome )
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-default" /> |
            @Html.ActionLink("Voltar à lista", "Index")
        </div>
    }
</div>

<script>
	$(document).ready(function () {
		// esconde a mensagem de alerta que apareça
		setTimeout(function () {
			$("#msg").fadeOut(1000);
		}, 6000);
	});

</script>

TennisApp/Views/Categorias/Details.cshtml
@model TennisApp.Models.Categoria

@{
    ViewBag.Title = "Detalhes";
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Detalhes</h2>

<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdCategoria }) |
    @Html.ActionLink("Voltar à lista", "Index")
</p>
<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Categorias/Edit.cshtml
@model TennisApp.Models.Categoria

@{
    ViewBag.Title = "Editar";
}
@if (TempData["Edit"] != null)
{
    <div id="msg" class="alert alert-warning fade-in">
        <strong>Categoria editada!</strong>
        A Categoria " @TempData["Edit"].ToString() " foi editada com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Categorias", FormMethod.Post, new { @class = "form-control"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdCategoria)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Categorias/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<TennisApp.Models.Categoria>

@{
    ViewBag.Title = "Lista de Categorias";
}
@if (TempData["Create"] != null)
{
    <div id="msg" class="alert alert-success fade in">
        <strong>Categoria criada!</strong>
        A Categoria " @TempData["Create"].ToString() " foi criada com sucesso.
    </div>
}
@if (TempData["Edit"] != null)
{
    <div id="msg" class="alert alert-warning fade in">
        <strong>Categoria editada!</strong>
        A Categoria " @TempData["Edit"].ToString() " foi editada com sucesso.
    </div>
}
@if (TempData["Delete"] != null)
{
    <div id="msg" class="alert alert-success fade in">
        <strong>Categoria editada!</strong>
        A Categoria " @TempData["Delete"].ToString() " foi eliminada com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Lista de Categorias</h2>
<div>
    @Html.ActionLink("Criar uma nova Categoria", "Create")
    @using (Html.BeginForm("Index", "Categorias", FormMethod.Get))
    {
        <b>Procurar por: </b>
        @Html.RadioButton("searchBy", "Categoria", true) <text>Categoria</text>
        @Html.RadioButton("searchBy", "Descricao", true) <text>Descrição</text>
        <br />
        @Html.TextBox("search", null, new { id = "txtSearch" })  <input type="submit" value="Procurar" />
    }

    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Categoria", "Index", new { sortBy = ViewBag.SortCategoriaParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Descricao)
            </th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4"> Não foi encontrado o que procura.</td>
            </tr>
        }

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdCategoria }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.IdCategoria }) |
                    @Html.ActionLink("Remover", "Delete", new { id = item.IdCategoria })
                </td>
            </tr>
        }

    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    searchBy = Request.QueryString["searchBy"],
    search = Request.QueryString["search"],
    sortBy = Request["sortBy"]
}),
new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })
</div>

<script>
	$(document).ready(function () {
		// esconde a mensagem de alerta que apareça
		setTimeout(function () {
			$("#msg").fadeOut(1000);
		}, 6000);
	});

</script>