TennisApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TennisApp.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Página de descrição da aplicação.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "A sua página de contacto.";

            return View();
        }
    }
}

TennisApp/Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TennisApp.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace TennisApp.Controllers
{
    public class NoticiasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Noticias
        [AllowAnonymous]
        [OutputCache(Duration = 10)]
        public ActionResult Index(string searchBy, string search, int? page, string sortBy, string categoriaString, string searchString)
        {
            ViewBag.SortAutorParameter = string.IsNullOrEmpty(sortBy) ? "Autor desc" : "";
            ViewBag.SortTituloParameter = sortBy == "Titulo" ? "Titulo desc" : "Titulo";
            ViewBag.SortRelevanciaParameter = sortBy == "Relevancia" ? "Relevancia desc" : "Relevancia";

            var categoriaList = new List<String>();
            var categoriasQry = from d in db.Categorias orderby d.Nome select d.Nome;

            categoriaList.AddRange(categoriasQry);
            ViewBag.categoriaString = new SelectList(categoriaList);

            var noticias = db.Noticias.AsQueryable();

            if (searchBy == "Autor")
            {
                noticias = noticias.Where(x => x.Criador.Nome.Contains(search) || search == null);
            }
            else if (searchBy == "Titulo")
            {
                noticias = noticias.Where(x => x.Titulo.Contains(search) || search == null);
            }
            else if (searchBy == "Relevancia")
            {
                noticias = noticias.Where(x => x.Relevancia.ToString() == search || search == null);
            }
            else if (!String.IsNullOrEmpty(categoriaString))
            {
                noticias = noticias.Where(x => x.Categorias.Select(c => c.Nome).Contains(categoriaString));
                //https://stackoverflow.com/questions/13405568/linq-unable-to-create-a-constant-value-of-type-xxx-only-primitive-types-or-enu
            }
            else if (searchString == "Torneios")
            {
                noticias = noticias.Where(x => x.Categorias.Select(c => c.Nome).Contains(searchString));
            }
            else if (searchString == "Clube")
            {
                noticias = noticias.Where(x => x.Categorias.Select(c => c.Nome).Contains(searchString));
            }
            else if (searchString == "Notícias")
            {
                noticias = noticias.Where(x => x.Categorias.Select(c => c.Nome).Contains(searchString));
            }
            else 
            {
                noticias = noticias.Where(x => x.Descricao.Contains(search) || search == null);
            }
            switch (sortBy)
            {
                case "Autor desc":
                    noticias = noticias.OrderByDescending(x => x.Criador.Nome);
                    break;
                case "Titulo desc":
                    noticias = noticias.OrderByDescending(x => x.Titulo);
                    break;
                case "Titulo":
                    noticias = noticias.OrderBy(x => x.Titulo);
                    break;
                case "Relevancia desc":
                    noticias = noticias.OrderByDescending(x => x.Relevancia);
                    break;
                case "Relevancia":
                    noticias = noticias.OrderBy(x => x.Relevancia);
                    break;
                default:
                    noticias = noticias.OrderBy(x => x.Criador.Nome);
                    break;
            }
            return View(noticias.ToPagedList(page ?? 1, 8));
        }

        // GET: Noticias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Noticia inválida";
                return RedirectToAction("Index");
            }
            Noticia noticia = db.Noticias.Find(id);
            if (noticia == null)
            {
                TempData["Error"] = "Noticia inválida";
                return RedirectToAction("Index");
            }
            return View(noticia);
        }

        // GET: Noticias/Create
        [ValidateInput(false)]
        [Authorize(Roles = "Jornalista")]
        public ActionResult Create()
        {
            // obtem a lista de Categorias");
            ViewBag.Categorias = db.Categorias.OrderBy(c => c.Nome);
            return View();
        }

        // POST: Noticias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Jornalista")]
        public ActionResult Create([Bind(Include = "Titulo,Descricao,Foto,TipoImagem,Relevancia,DataPublicacao,DataLimiteVisualizacao,Visivel,CriadorFK")] Noticia noticia,
            int[] categorias, HttpPostedFileBase fotografia)
        {
            if (categorias != null)
            {
                if (fotografia != null)
                {
                    //Selecciona o último id  e incrementa 1
                    var NoticiaID = db.Noticias.OrderByDescending(d => d.IdNoticia).FirstOrDefault().IdNoticia + 1;

                    // atribui o novo ID ao objeto que veio da View
                    noticia.IdNoticia = NoticiaID;

                    //Recolhe a data actual
                    noticia.DataPublicacao = DateTime.Now;

                    string pic = System.IO.Path.GetFileName(fotografia.FileName);
                    noticia.Foto = pic;
                    //guardar caminho para a foto
                    string path = System.IO.Path.Combine(Server.MapPath("/Imagens"), pic);

                    fotografia.SaveAs(path);// file is uploaded

                    // save the image path path to the database or you can send image
                    // directly to database
                    // in-case if you want to store byte[] ie. for DB
                    using (MemoryStream ms = new MemoryStream())
                    {
                        fotografia.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }

                    //atribuir as categorias à notícia
                    // iterar pelo array de categorias e criar uma lista de categorias
                    var listaCategorias = new List<Categoria>();
                    foreach (var cat in categorias)
                    {
                        listaCategorias.Add(db.Categorias.Where(x=>x.IdCategoria == cat).FirstOrDefault());
                    }
                    noticia.Categorias = listaCategorias;

                    // atribuir o ID do dono da notícia à notícia
                    noticia.CriadorFK = db.Utilizadores.Where(u => u.UserName.Equals(User.Identity.Name)).FirstOrDefault().IdUtilizador;

                    StringBuilder sbNoticias = new StringBuilder();
                    sbNoticias.Append(HttpUtility.HtmlEncode(noticia.Descricao));

                    //evitar ataques SQL injection
                    sbNoticias.Replace("&lt;b&gt;", "<b>");
                    sbNoticias.Replace("&lt;/b&gt;", "</b>");
                    sbNoticias.Replace("&lt;u&gt;", "<u>");
                    sbNoticias.Replace("&lt;/u&gt;", "</u>");
                    sbNoticias.Replace("\r\n", "<br />");

                    noticia.Descricao = sbNoticias.ToString();

                    string strTitulo = HttpUtility.HtmlEncode(noticia.Titulo);
                    noticia.Titulo = strTitulo;

                    if (ModelState.IsValid)
                    {
                        db.Noticias.Add(noticia);
                        db.SaveChanges();
                        TempData["Create"] = "" + noticia.Titulo;
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    TempData["Error"] = "Não adicionou uma Imagem à Notícia";
                }
            }
            else
            {
                TempData["Error"] = "Não slecionou pelo menos uma Categoria para a Notícia";
            }
            // obtem a lista de Categorias;
            ViewBag.Categorias = db.Categorias.OrderBy(c => c.Nome);
            return View(noticia);
        }

        // GET: Noticias/Edit/5
        [ValidateInput(false)]
        [Authorize(Roles = "Jornalista,Moderador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Noticia inválida";
                return RedirectToAction("Index");
            }
            Noticia noticia = db.Noticias.Find(id);
            if (noticia == null)
            {
                TempData["Error"] = "Notícia inválida";
                return RedirectToAction("Index");
            }

            // obtem a lista de Categorias;
            ViewBag.Categorias = db.Categorias.OrderBy(c => c.Nome);

            // verificar se a pessoa que edita a notícia é um Moderador
            if (User.IsInRole("Moderador"))
            {
                return View(noticia);
            }

            // verificar se a pessoa que edita a notícia é o seu autor
            if (noticia.Criador.UserName.Equals(User.Identity.Name))
            {
                return View(noticia);
            }
            TempData["Error"] = "Não tem permissões para editar esta notícia";
            return RedirectToAction("Index");
        }

        // POST: Noticias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]

TennisApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title </h2>
<h3>Ténis Clube de Tomar</h3>

<p>Este website foi desenvolvido no âmbito da cadeira de Tecnologias Internet II, curso de Engenharia Informática.</p>

TennisApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contactos";
}
<h2>@ViewBag.Title.</h2>

<div class="container-base">
    <div class="row">
        <div class="col-md-10">
            <h3>A minha Informação</h3>
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <address>
                <strong>Discente:</strong>Pedro Dias<br />
                <strong>Número:</strong>17108<br />
            </address>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <address>
                <strong>Email principal :</strong>   <a href="diaspedro1999@hotmail.com">diaspedro1999@hotmail.com</a><br />
                <strong>Email IPT :</strong> <a href="aluno17108@ipt.pt">aluno17108@ipt.pt</a>
            </address>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <br />
            <h4>Registo "Amiinistrador" do website</h4>
            <address>
                <strong>Utilizador:</strong>admin@a.aa<br />
                <strong>Password:</strong>123_Aa<br />
                <strong>Nome:</strong>Admin<br />
            </address>
            <h4>Registo "Moderador" do website</h4>
            <address>
                <strong>Utilizador:</strong>c@c.cc<br />
                <strong>Password:</strong>123_Aa<br />
                <strong>Nome:</strong>Fábio Ferreira<br />
            </address>
            <h4>Registo "Jornalista" do website</h4>
            <address>
                <strong>Utilizador:</strong>a@a.aa<br />
                <strong>Password:</strong>123_Aa<br />
                <strong>Nome:</strong>Pedro Dias<br />
            </address>
            <address>
                <strong>Utilizador:</strong>b@b.bb<br />
                <strong>Password:</strong>123_Aa<br />
                <strong>Nome:</strong>Fábio Salvador<br />
            </address>
            <h4>Registo "Default" do website (exemplo pois há vários)</h4>
            <address>
                <strong>Utilizador:</strong>d@d.dd<br />
                <strong>Password:</strong>123_Aa<br />
                <strong>Nome:</strong>Tiago Henriques<br />
            </address>
        </div>
    </div>

TennisApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Página Inicial";
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}

<div class="container">
    <div class="jumbotron">
        <img src="~/Imagens/simboloclube.jpg" style="width:150px;" /><h1>TÉNIS CLUBE DE TOMAR</h1>
        <p class="lead"></p>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2>Torneios</h2>
            <p>Notícias referentes a torneios do clube a decorrer ou já terminados.</p>
            <p>@Html.ActionLink("Ir", "Index", "Noticias", new { searchString = "Torneios" }, new { @class = "btn btn-default" })</p>
        </div>
        <div class="col-md-4">
            <h2>Clube</h2>
            <p>Notícias referentes a atletas do clube ou o próprio clube e treinadores do clube.</p>
            <p>@Html.ActionLink("Ir", "Index", "Noticias", new { searchString = "Clube" }, new { @class = "btn btn-default" })</p>
        </div>
        <div class="col-md-4">
            <h2>Torneios</h2>
            <p>Notícias referentes a jogadores internacionais, tópicos sobre ténis e torneios internacionais.</p>
            <p>@Html.ActionLink("Ir", "Index", "Noticias", new { searchString = "Notícias" }, new { @class = "btn btn-default" })</p>
        </div>
    </div>
</div>