TennisApp/Models/Utilizador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TennisApp.Models
{
    public class Utilizador
    {
        public Utilizador()
        {
            this.Noticias = new HashSet<Noticia>();
            this.Comentarios = new HashSet<Comentario>();
        }

        [Key]
        public int IdUtilizador { get; set; }

        [Required(ErrorMessage = "É necessário um {0}.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "O {0} deve ter entre {2} e {1} caracteres.")]
        public string Nome { get; set; }

        //[Required(ErrorMessage = "É necessário um Tipo de Utilizador.")]
        public string Tipo { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "Não é um email válido.")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber, ErrorMessage = "Não é um número de telémovel válido.")]
        [StringLength(9)]
        [RegularExpression("9[1236][0-9]{7}", ErrorMessage = "O {0} deve ter apenas 9 carateres numéricos.")]
        public string Telemovel { get; set; }

        [Required(ErrorMessage = "É necessária uma {0}.")]
        [DisplayName("Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNasc { get; set; }

        // referencia um utilizador da tabela do USERs
        //public virtual AspNetUsers AspNetUsers { get; set; }
        public string UserName { get; set; }


        public virtual ICollection<Noticia> Noticias { get; set; }
        public virtual ICollection<Comentario> Comentarios { get; set; }

    }
}

TennisApp/Controllers/UtilizadorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TennisApp.Models;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;

namespace TennisApp.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UtilizadorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Utilizadors
        //metodo search por tipo e nome
        [AllowAnonymous]
        [OutputCache(Duration = 10)]
        public ActionResult Index(string searchBy, string search, int? page, string sortBy)
        {
            ViewBag.SortNameParameter = string.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.SortUsernameParameter = sortBy == "Username" ? "Username desc" : "Username";
            ViewBag.SortTipoParameter = sortBy == "Tipo" ? "Tipo desc" : "Tipo";

            var utilizadores = db.Utilizadores.AsQueryable();

            if (searchBy == "Nome")
            {
                utilizadores = utilizadores.Where(x => x.Nome.Contains(search) || search == null);
            }
            else if (searchBy == "Tipo")
            {
                utilizadores = utilizadores.Where(x => x.Tipo.Contains(search) || search == null);
            }
            else
            {
                utilizadores = utilizadores.Where(x => x.UserName.Contains(search) || search == null);
            }
            switch (sortBy)
            {
                case "Name desc":
                    utilizadores = utilizadores.OrderByDescending(x => x.Nome);
                    break;
                case "Username desc":
                    utilizadores = utilizadores.OrderByDescending(x => x.UserName);
                    break;
                case "Username":
                    utilizadores = utilizadores.OrderBy(x => x.UserName);
                    break;
                case "Tipo desc":
                    utilizadores = utilizadores.OrderByDescending(x => x.Tipo);
                    break;
                case "Tipo":
                    utilizadores = utilizadores.OrderBy(x => x.Tipo);
                    break;
                default:
                    utilizadores = utilizadores.OrderBy(x => x.Nome);
                    break;
            }
            return View(utilizadores.ToPagedList(page ?? 1, 5));
        }

        // GET: Utilizadors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Utilizador inválido";
                return RedirectToAction("Index");
            }
            Utilizador utilizador = db.Utilizadores.Find(id);
            if (utilizador == null)
            {
                TempData["Error"] = "Utilizador inválido";
                return RedirectToAction("Index");
            }
            return View(utilizador);
        }

        // GET: Utilizadors/Create
        [ValidateInput(false)]
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utilizadors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [AllowAnonymous]
        public ActionResult Create([Bind(Include = "IdUtilizador,Nome,Tipo,Email,Telemovel,DataNasc,UserName")] Utilizador utilizador)
        {

            string strNome = HttpUtility.HtmlEncode(utilizador.Nome);
            utilizador.Nome = strNome;

            string strUsername = HttpUtility.HtmlEncode(utilizador.UserName);
            utilizador.UserName = strUsername;

            if (ModelState.IsValid)
            {
                db.Utilizadores.Add(utilizador);
                db.SaveChanges();
                TempData["Create"] = "" + utilizador.Nome;
                return RedirectToAction("Index");
            }

            return View(utilizador);
        }

        // GET: Utilizadors/Edit/5
        [ValidateInput(false)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Utilizador inválido";
                return RedirectToAction("Index");
            }
            Utilizador utilizador = db.Utilizadores.Find(id);
            if (utilizador == null)
            {
                TempData["Error"] = "Utilizador inválido";
                return RedirectToAction("Index");
            }
            return View(utilizador);
        }

        // POST: Utilizadors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "IdUtilizador,Nome,Tipo,Email,Telemovel,DataNasc,UserName")] Utilizador utilizador)
        {
            string strNome = HttpUtility.HtmlEncode(utilizador.Nome);
            utilizador.Nome = strNome;

            string strUsername = HttpUtility.HtmlEncode(utilizador.UserName);
            utilizador.UserName = strUsername;

            if (ModelState.IsValid)
            {
                //alterar dados do Utilizador da parte da aplicação
                //criar os dados do Utilizador
                ApplicationDbContext db = new ApplicationDbContext();
                var user = new ApplicationUser { UserName = utilizador.Email, Email = utilizador.Email };
              //  user = db.Users.Find(user);
              //  User
            //  UserManager.

                db.Entry(utilizador).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Edit"] = "" + utilizador.Nome;
                return RedirectToAction("Index");
            }
            return View(utilizador);
        }

        // GET: Utilizadors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = "Utilizador inválido";
                return RedirectToAction("Index");
            }
            Utilizador utilizador = db.Utilizadores.Find(id);
            if (utilizador == null)
            {
                TempData["Error"] = "Utilizador inválido";
                return RedirectToAction("Index");
            }
            return View(utilizador);
        }

        // POST: Utilizadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utilizador utilizador = db.Utilizadores.Find(id);
            db.Utilizadores.Remove(utilizador);
            db.SaveChanges();
            TempData["Delete"] = utilizador.Nome;
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TennisApp/Views/Utilizadors/Create.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using TennisApp.Models;

@model TennisApp.Models.RegisterViewModel


@{
    ViewBag.Title = "Criar";
    //Preenche as dropdowns e a lista de roles existt
    List<string> roles;
    List<string> users;
    using (var context = new ApplicationDbContext())
    {
        var roleStore = new RoleStore<IdentityRole>(context);
        var roleManager = new RoleManager<IdentityRole>(roleStore);

        var userStore = new UserStore<ApplicationUser>(context);
        var userManager = new UserManager<ApplicationUser>(userStore);

        users = (from u in userManager.Users select u.UserName).ToList();
        roles = (from r in roleManager.Roles select r.Name).ToList();
    }
    ViewBag.Roles = new SelectList(roles);
    ViewBag.Users = new SelectList(users);
    ViewBag.RolesList = roles;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Create"] != null)
{
    <div id="msg" class="alert alert-success fade-in">
        <strong>Utilizador criado!</strong>
        O Utilizador " @TempData["Create"].ToString() " foi criado com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Criar</h2>


@using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>

    <hr />
    //Nome da pessoa
    <div class="form-group">
        @Html.LabelFor(m => m.Utilizador.Nome, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Utilizador.Nome, new { @class = "form-control" })
        </div>
    </div>
    //telemovel da pessoa
    <div class="form-group">
        @Html.LabelFor(m => m.Utilizador.Telemovel, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Utilizador.Telemovel, new { @class = "form-control" })
        </div>
    </div>
    //Data de Nasc. da pessoa
    <div class="form-group">
        @Html.LabelFor(m => m.Utilizador.DataNasc, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Utilizador.DataNasc, new { @class = "form-control" })
        </div>
    </div>

    <hr />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Registar" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Utilizadors/Delete.cshtml
@model TennisApp.Models.Utilizador

@{
    ViewBag.Title = "Demover";
}
@if (TempData["Delete"] != null)
{
    <div id="msg" class="alert alert-success fade-in">
        <strong>Utilizador editada!</strong>
        O Utilizador " @TempData["Delete"].ToString() " foi eliminado com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Demover</h2>

<h3>Tem a certeza que pretende remover?</h3>
<div>
    <h4>Utilizador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telemovel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telemovel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNasc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-default" /> |
            @Html.ActionLink("Voltar à lista", "Index")
        </div>
    }
</div>

TennisApp/Views/Utilizadors/Details.cshtml
@model TennisApp.Models.Utilizador

@{
    ViewBag.Title = "Detalhes";
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Detalhes</h2>

<div>
    <h4>Utilizador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telemovel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telemovel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNasc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdUtilizador }) |
    @Html.ActionLink("Voltar à lista", "Index")
</p>
<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Utilizadors/Edit.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using TennisApp.Models;

<script src="~/Scripts/jquery-1.10.2.js"></script>

@model TennisApp.Models.Utilizador

@{
    ViewBag.Title = "Editar";
    //Preenche as dropdowns e a lista de roles existt
    List<string> roles;
    List<string> users;
    using (var context = new ApplicationDbContext())
    {
        var roleStore = new RoleStore<IdentityRole>(context);
        var roleManager = new RoleManager<IdentityRole>(roleStore);

        var userStore = new UserStore<ApplicationUser>(context);
        var userManager = new UserManager<ApplicationUser>(userStore);

        users = (from u in userManager.Users select u.UserName).ToList();
        roles = (from r in roleManager.Roles select r.Name).ToList();
    }
    ViewBag.Roles = new SelectList(roles);
    ViewBag.Users = new SelectList(users);
    ViewBag.RolesList = roles;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Edit"] != null)
{
    <div id="msg" class="alert alert-warning fade-in">
        <strong>Utilizador editado!</strong>
        O Utilizador " @TempData["Edit"].ToString() " foi editado com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade-in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utilizador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdUtilizador)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Tipo", ViewBag.Roles as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telemovel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telemovel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telemovel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNasc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNasc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNasc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>

TennisApp/Views/Utilizadors/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using TennisApp.Models;

@model IPagedList<TennisApp.Models.Utilizador>

@{
    ViewBag.Title = "Gestão de Utilizadores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Create"] != null)
{
    <div id="msg" class="alert alert-success fade in">
        <strong>Utilizador criado!</strong>
        O Utilizador " @TempData["Create"].ToString() " foi criado com sucesso.
    </div>
}
@if (TempData["Edit"] != null)
{
    <div id="msg" class="alert alert-warning fade in">
        <strong>Utilizador editado!</strong>
        O Utilizador " @TempData["Edit"].ToString() " foi editado com sucesso.
    </div>
}
@if (TempData["Delete"] != null)
{
    <div id="msg" class="alert alert-success fade in">
        <strong>Utilizador editado!</strong>
        O Utilizador " @TempData["Delete"].ToString() " foi eliminado com sucesso.
    </div>
}
@if (TempData["Error"] != null)
{
    <div id="msg" class="alert alert-danger fade in">
        <strong>Erro!</strong>
        Ocorreu um erro: @TempData["Error"].ToString() .
    </div>
}
<script src="~/Scripts/jquery-1.10.2.js"></script>

<div>

    <div class="row" style="padding:5px;">
        <div class="col col-md-9" style="font-size:14px;">
            @using (Html.BeginForm("Index", "Utilizadors", FormMethod.Get))
            {
                <div class="row justify-content-center my-3">
                    <label style="float:left; margin-right:10px;">Procurar por:</label>
                    <text>Nome</text>@Html.RadioButton("searchBy", "Nome", false)
                    <text>UserName</text>@Html.RadioButton("searchBy", "UserName", false)
                </div>
                <div class="row">
                    @Html.TextBox("search")  <input type="submit" value="Procurar" />
                </div>
            }
        </div>
        <div class="col-12 col-lg-2" style="font-size:14px;">
            @if (User.IsInRole("Administrador"))
            {
                <label>@Html.ActionLink("Criar um novo Utilizador", "Create")</label>
            }
        </div>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Nome", "Index", new { sortBy = ViewBag.SortNameParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
            </th>
            <th>
                @Html.ActionLink("Tipo", "Index", new { sortBy = ViewBag.SortTipoParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Telemovel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DataNasc)
            </th>
            <th>
                @Html.ActionLink("Username", "Index", new { sortBy = ViewBag.SortUsernameParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
            </th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
            {
            <tr>
                <td colspan="4"> Não foi encontrado o que procura.</td>
            </tr>
        }
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telemovel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataNasc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdUtilizador }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.IdUtilizador }) |
                    @Html.ActionLink("Remover", "Delete", new { id = item.IdUtilizador })
                </td>
            </tr>
        }

    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    searchBy = Request.QueryString["searchBy"],
    search = Request.QueryString["search"],
    sortBy = Request["sortBy"]
}),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })
</div>

<script>
    $(document).ready(function () {
        // esconde a mensagem de alerta que apareça
        setTimeout(function () {
            $("#msg").fadeOut(1000);
        }, 6000);
    });

</script>